name: Build and Deploy Allure Report

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and run tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin

      - name: Send Email Notification (only on success)
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false

          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}

          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ secrets.GMAIL_USERNAME }}

          subject: Allure Test Report - Swag Lab Project

          body: |
            Build SUCCESS ✅

            Report URL:
            https://shashika011.github.io/Swag-Lab-Project/
