name: Build and Deploy Allure Report

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn clean test
        continue-on-error: true

      - name: Check Allure results folder
        run: |
          if [ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ]; then
            echo "Allure results generated"
            ls target/allure-results
          else
            echo "No Allure results found"
          fi

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 30

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Get Report URL
        id: report
        run: echo "url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_OUTPUT

      - name: Debug MAIL_USERNAME (safe check)
        run: |
          if [ -z "${{ secrets.MAIL_USERNAME }}" ]; then
            echo "MAIL_USERNAME is EMPTY"
          else
            echo "MAIL_USERNAME is SET"
          fi

      - name: Send Email with Allure Report Link
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          from: ${{ secrets.MAIL_USERNAME }}
          to: your_email@gmail.com

          subject: Allure Test Report - ${{ github.repository }}

          body: |
            Allure report generated successfully.

            Report URL:
            ${{ steps.report.outputs.url }}
